version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend folder
    ports:
      - "3000:3000"  # Expose port 3000 (for Next.js or Node.js)
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Path to your backend directory
    ports:
      - "8000:8000"  # Expose port 8000 (for Django or other Python apps)
    environment:
      - DJANGO_SECRET_KEY=your_secret_key  # Replace with your Django secret key or other env vars
    networks:
      - app-network

  db:
      image: mysql:8
      container_name: notes-db
      restart: always
      environment:
        MYSQL_DATABASE: notesdb
        MYSQL_USER: notesuser
        MYSQL_PASSWORD: notespass
        MYSQL_ROOT_PASSWORD: rootpass
      ports:
        - "3307:3306"
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: